FROM node

WORKDIR /app

COPY package.json /app

# The RUN command will be executed when the image is created.
RUN npm install

COPY . /app

# It defines an argument with a value(80) default. This argument can be passed on build the image.
# Note that arguments can not be used on the CMD command, because it's a runtime command.
ARG DEFAULT_PORT=80

# It Defines an environment variable.
#ENV PORT 80
ENV PORT %DEFAULT_PORT

# Expose ports on Dockerfile is optional, actually it doesn't do anything. It's only to document purpose.
# EXPOSE 80 
EXPOSE $PORT


# Create an anonymous and temporary volume. This folder will be recreated when the container was stoped and started again, therefore their content won't be held:
VOLUME ["/app/any_folder"]

# The CMD command will be executed when the container execute and must to be the last command in this file.
# Pay attention that this command will be override with you run the container passing a command like this: "docker run node npm init"
CMD ["node", "server.js"]

# This command is similar to the "CMD" command, but with a significant difference. 
# The diference is that with ENTRYPOINT when you run a container passing a command, this command will be appended to the commands in the ENTRYPOINT.
# So, this way you can run the container like that: "docker run node init"
ENTRYPOINT ["npm"]